name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: textarea
    attributes:
      label: Describe the bug
      description: A concise description of what issue you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior. **Example:** "1. Go to the Github stats section. 2. Click on the desired github stats. 3. See error."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen. **Example:** "I expect Github stats should get selected and displayed."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Videos
      description: |
        If applicable, add screenshots or videos to help explain your problem.

        **Tip:** You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: What device are you using?
      description: Please select the device you're using.
      multiple: true
      options:
        - Desktop
        - Mobile
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: Please select the operating system you're using. **Example:** "Windows". If you're using multiple Operating systems, please select all that apply.
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Android
        - IOS
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What browsers are you seeing the problem on?
      description: Please select the browser you're using. If you're using multiple browsers, please select all that apply.
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Internet Explorer
        - Other
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
